### ISSUE TITLE
Error while deserialization of graph inside nodes

### ISSUE THREAD

**Issue by mraunak** [ModECI/MDF#136] opened 2021-09-07 22:26 UTC
Current development in MDF supports serialization of 'Graph' object inside nodes(ordered dictionary of 'Node' objects inside Graph). However, it does not support deserialization of the same.

Reason for failure: Parser considers Graph inside nodes as Node, hence failing 

Test cases of failure are available at: https://github.com/ModECI/MDF/blob/feature/metadata/tests/test_model.py

def test_graph_in_graphs(tmpdir):
.....

One hack to fix it is while loading JSON file back using load_mdf, apply a check for objects(Graph/Node) inside Nodes to differentiate between Node and Graph, by looking if 'nodes' present in that object.

**Comment by mraunak** [comment] 2021-09-17 22:44
As per the discussion, there should be a "reference" attribute in the allowed fields for the "Node" object which should point towards the "Graph" object. 

e.g. there is a nested graph mdf_graph2=Graph(id="mdf2") if this Graph is inside a Node_A, Node_A =Node(id='A',reference='mdf2')

The 'Graph' object should be present inside the graphs of the model. 

Next steps to update the execution engine to handle the input and output of the Graph object inside the Node.

**Comment by 29riyasaxena** [comment] 2022-04-02 11:47
> Current development in MDF supports serialization of 'Graph' object inside nodes(ordered dictionary of 'Node' objects inside Graph). However, it does not support deserialization of the same.
> 
> Reason for failure: Parser considers Graph inside nodes as Node, hence failing
> 
> Test cases of failure are available at: https://github.com/ModECI/MDF/blob/feature/metadata/tests/test_model.py
> 
> def test_graph_in_graphs(tmpdir): .....
> 
> One hack to fix it is while loading JSON file back using load_mdf, apply a check for objects(Graph/Node) inside Nodes to differentiate between Node and Graph, by looking if 'nodes' present in that object.

Hi! This issue seems interesting to me and I have got what it is asking for. Can you please guide me on what to learn to write, (like json or something else) the code. I know python and javascript. @pgleeson @sanjayankur31

**Comment by 29riyasaxena** [comment] 2022-04-04 11:35
> Thanks for your interest in this @29riyasaxena. Unfortunately resolving this issue will require a major extension to the core specification of MDF (at the moment subgraphs aren't really supported at all), followed by tests on the implentation in the various target environments. It's more of a potential activity for during the internship rather than beforehand. 

I did modified the utils file and tested it. I got no error. I made a commit, can you please check that.

**Comment by parikshit14** [comment] 2022-04-07 19:01
hi @pgleeson, I was working on this issue as well, what I inferred was during **_parsing_element** this issue arises in which it cannot deserialize the nested graph object. So what I was trying was, to first make a reference node inside and then de-reference it during the load_json process which works fine and now I am trying to do the same for graphs.
I know this is a big task and can be taken during the internship but if this task can be divided into smaller tasks like 

**firstly** we need to decide how are we going to implement this

- saving the JSON particularly the graph ones in such a way that during the reading process they can be expanded.

or 
- only during the reading process a step can be added to check the type (simple or nested) and then the (extra)deserialization step for the nested ones.

and then according to the most suited approach, we can further divide 

1. read/write in a referenced manner
2. Autodetect nested graphs

.
.
.

**Comment by pgleeson** [comment] 2022-04-08 16:03
@parikshit14 I appreciate your efforts on this, but the wider issue we're trying to solve (how do we enable subgraphs in MDF) has been discussed in more detail in our weekly developer meetings after this issue was opened, and the problem is not well described currently in this issue. 

It's not simply a case of what can/can't currently be serialised, we need to decide on the implications for all the target simulators before we change the core specification, and then prototype/test various options. For that reason it's probably best to close this issue and open more specific ones when we start to work on this.

**Closed by pgleeson** 2022-04-08 16:03 UTC
